# Generated by Django 5.1.2 on 2025-01-09 17:33

import Exercise.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('chest_upper', 'سینه - بالا سینه (Upper Chest)'), ('chest_middle', 'سینه - میانه سینه (Mid Chest)'), ('chest_lower', 'سینه - زیر سینه (Lower Chest)'), ('shoulders_anterior', 'سرشانه - دلتوئید جلویی (Anterior Deltoid)'), ('shoulders_lateral', 'سرشانه - دلتوئید میانی (Lateral Deltoid)'), ('shoulders_posterior', 'سرشانه - دلتوئید پشتی (Posterior Deltoid)'), ('biceps', 'جلو بازو (Biceps)'), ('triceps', 'پشت بازو (Triceps)'), ('back', 'پشت/زیربغل (Back)'), ('quadriceps', 'جلو ران (Quadriceps)'), ('hamstrings', 'پشت پا (Hamstrings)'), ('calves', 'ساق پا (Calves)'), ('abs_upper', 'شکم - بالا (Upper Abs)'), ('abs_middle', 'شکم - میانه (Middle Abs)'), ('abs_lower', 'شکم - پایین (Lower Abs)'), ('obliques', 'پهلو (Obliques)'), ('cardio', 'هوازی (Cardio)'), ('warmup_cooldown', 'گرم/سرد (Warm-up/Cool-down)')], max_length=50, verbose_name='گروه عضلانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام حرکت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات حرکت')),
                ('training_video', models.FileField(blank=True, null=True, upload_to=Exercise.models.exercise_video_path, verbose_name='ویدئوی آموزشی')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_id', models.CharField(max_length=50, unique=True)),
                ('chunk_size', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('processed_chunks', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercise')),
            ],
        ),
    ]
