# Generated by Django 5.1.2 on 2025-01-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_delete_uploadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=36)),
                ('chunk_number', models.PositiveIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('chunk_data', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercise')),
            ],
            options={
                'ordering': ['file_id', 'chunk_number'],
                'indexes': [models.Index(fields=['file_id', 'chunk_number'], name='Exercise_vi_file_id_5a94cb_idx'), models.Index(fields=['exercise'], name='Exercise_vi_exercis_d5cd34_idx')],
                'unique_together': {('file_id', 'chunk_number')},
            },
        ),
    ]
