# Generated by Django 5.1.2 on 2025-01-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0003_videouploadchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'در حال آپلود'), ('completed', 'تکمیل شده'), ('failed', 'خطا در آپلود')], default='completed', max_length=20, verbose_name='وضعیت آپلود'),
        ),
        migrations.DeleteModel(
            name='VideoUploadChunk',
        ),
    ]
