# Generated by Django 5.1.2 on 2025-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0005_remove_exercise_upload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_chunks', models.IntegerField()),
                ('received_chunks', models.IntegerField(default=0)),
                ('exercise_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['file_id'], name='Exercise_vi_file_id_16c878_idx')],
            },
        ),
    ]
