# Generated by Django 5.1.2 on 2025-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0006_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='exercise_id',
            field=models.IntegerField(null=True),
        ),
    ]
