# Generated by Django 5.1.2 on 2025-02-28 19:52

import Exercise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0007_alter_videoupload_exercise_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoupload',
            name='Exercise_vi_file_id_16c878_idx',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'سینه'), ('shoulders', 'سرشانه'), ('legs', 'پا'), ('core', 'شکم'), ('biceps', 'جلو بازو (Biceps)'), ('triceps', 'پشت بازو (Triceps)'), ('back', 'پشت/زیربغل (Back)'), ('cardio', 'هوازی (Cardio)'), ('warmup_cooldown', 'گرم/سرد (Warm-up/Cool-down)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='training_video',
            field=models.FileField(blank=True, null=True, upload_to=Exercise.models.exercise_video_path),
        ),
    ]
