# Generated by Django 5.1.2 on 2025-04-23 09:11

import Exercise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0008_remove_videoupload_exercise_vi_file_id_16c878_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات حرکت'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'سینه'), ('shoulders', 'سرشانه'), ('legs', 'پا'), ('core', 'شکم'), ('biceps', 'جلو بازو'), ('triceps', 'پشت بازو'), ('back', 'زیربغل'), ('cardio', 'هوازی'), ('warmup_cooldown', 'گرم/سرد')], max_length=50, verbose_name='گروه عضلانی'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام حرکت'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='training_video',
            field=models.FileField(blank=True, null=True, upload_to=Exercise.models.exercise_video_path, verbose_name='ویدئوی آموزشی'),
        ),
        migrations.AddIndex(
            model_name='videoupload',
            index=models.Index(fields=['file_id'], name='Exercise_vi_file_id_16c878_idx'),
        ),
    ]
