# Generated by Django 5.1.2 on 2025-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='وزن (کیلوگرم)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='قد (سانتی\u200cمتر)')),
                ('injuries', models.TextField(blank=True, null=True, verbose_name='آسیب\u200cدیدگی\u200cها')),
                ('training_history', models.TextField(blank=True, null=True, verbose_name='سابقه تمرین')),
                ('motivation_goal', models.CharField(blank=True, choices=[('professional_bodybuilding', 'بدنسازی حرفه\u200cای و مسابقات'), ('health_fitness', 'سلامتی و علاقه به ورزش')], max_length=50, null=True, verbose_name='هدف انگیزه ورزشی')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن همراه')),
                ('telegram_whatsapp_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلگرام / واتساپ')),
                ('body_test_file', models.FileField(blank=True, null=True, upload_to='body_tests/', verbose_name='فایل تست بادی')),
                ('supplements', models.TextField(blank=True, null=True, verbose_name='مصرف مکمل\u200cها و داروها')),
                ('unique_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد اختصاصی')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecycledCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='کد قابل بازیافت')),
            ],
        ),
    ]
