# Generated by Django 5.1.2 on 2025-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthleteProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='gym_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام باشگاه'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف'),
        ),
    ]
