# Generated by Django 5.1.2 on 2025-01-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AthleteProfile', '0001_initial'),
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='AthleteProfile.athleteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_reps', models.CharField(blank=True, choices=[('3x12', '12×3'), ('12-10-8', '12-10-8'), ('3x10', '10×3'), ('3x20', '20×3'), ('13-11-9', '13-11-9'), ('3x25', '25×3'), ('۵ دقیقه', '۵ دقیقه'), ('3x15', '15×3'), ('3x8', '8×3'), ('3x9', '9×3'), ('3x60', '60×3'), ('3x70', '70×3'), ('3x100', '100×3'), ('3x90', '90×3'), ('3x6', '6×3'), ('3x5', '5×3'), ('4x6', '6×4'), ('4x8', '8×4'), ('4x9', '9×4'), ('4x12', '12×4'), ('4x10', '10×4'), ('4x12', '12×4'), ('17-13-11', '17-13-11'), ('10-8-6', '10-8-6'), ('8-6-4', '8-6-4'), ('6-4-2', '6-4-2'), ('۲۰ ثانیه', '۲۰ ثانیه'), ('۲۰ دقیقه', '۲۰ دقیقه'), ('۴۰ ثانیه', '۴۰ ثانیه')], max_length=50, null=True, verbose_name='ست و تکرار')),
                ('is_superset', models.BooleanField(default=False, verbose_name='سوپرسِت')),
                ('session_number', models.IntegerField(blank=True, null=True, verbose_name='شماره جلسه')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='Exercise.exercise')),
                ('paired_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superset_pairs', to='Exercise.exercise', verbose_name='تمرین سوپرسِت')),
                ('paired_superset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_superset_pairs', to='Exercise.exercise', verbose_name='تمرین تری ست')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='Train.trainingplan')),
            ],
        ),
    ]
