# Generated by Django 5.1.2 on 2025-01-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AthleteProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('before_breakfast', 'قبل صبحانه (ناشتا)'), ('morning', 'صبحانه'), ('after_breakfast', 'بعد صبحانه'), ('before_lunch', 'قبل ناهار'), ('noon', 'ناهار'), ('after_lunch', 'بعد ناهار'), ('mid_afternoon', 'میان\u200cوعده عصر'), ('before_dinner', 'قبل شام'), ('evening', 'شام'), ('after_dinner', 'بعد شام'), ('before_bed', 'شب قبل خواب'), ('pre_workout', 'قبل از تمرین'), ('post_workout', 'بعد از تمرین')], max_length=50, verbose_name='زمان وعده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات وعده')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='مقدار غذا (واحد)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food', verbose_name='غذا')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.meal', verbose_name='وعده غذایی')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(through='Food.MealFood', to='Food.food', verbose_name='غذاهای وعده'),
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ شروع برنامه')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای مربی')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleteProfile.athleteprofile', verbose_name='ورزشکار')),
                ('meals', models.ManyToManyField(to='Food.meal', verbose_name='وعده\u200cهای غذایی')),
            ],
        ),
    ]
